package handlers

var apis = []string{
	"https://api.publicapis.org/entries",
	"https://catfact.ninja/fact",
	"https://api.coindesk.com/v1/bpi/currentprice.json",
	"https://www.boredapi.com/api/activity",
	"https://api.agify.io?name=meelad",
	"https://api.genderize.io?name=luc",
	"https://api.nationalize.io?name=nathaniel",
	"https://datausa.io/api/data?drilldowns=Nation&measures=Population",
	"https://dog.ceo/api/breeds/image/random",
	"https://ipinfo.io/161.185.160.93/geo",
	"https://official-joke-api.appspot.com/random_joke",
	"https://randomuser.me/api/",
	"https://api.zippopotam.us/us/33162",
	"https://api.agify.io?name=bella",
	"https://www.boredapi.com/api/activity",
	"https://api.coinbase.com/v2/currencies",
	"https://api.coingecko.com/api/v3/exchange_rates",
	"https://www.cryptingup.com/api/markets",
	"https://freegeoip.app/json/",
	"https://api.imgflip.com/get_memes",
	"https://api.ipify.org/?format=json",
	"https://api.nationalize.io/?name=michael",
	"https://random.dog/woof.json",
	"https://xkcd.com/info.0.json",
	"https://world.openfoodfacts.org/api/v0/product/737628064502.json",
	"https://randomuser.me/api/",
	"https://date.nager.at/api/v2/publicholidays/2020/US",
	"https://api.openbrewerydb.org/breweries",
	"https://api.zippopotam.us/us/90210",
}
